modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/OtisGoodman/Spooky-Stuff"
license="GNU"

[[mods]]
modId="spookystuff"
updateJSONURL="https://github.com/OtisGoodman/Spooky-Stuff"
version="${version}"
displayName="Spooky Stuff"
displayURL="https://github.com/OtisGoodman/Spooky-Stuff"
credits="Darkhax for the making spookyjam contest."
authors="Otis_Goodman"
description='''
Spooky Stuff is an entry for MMD's Spooky Jam 2020, which adds MISC fall/spooky items and blocks.
'''

[[dependencies.spookystuff]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spookystuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.spookystuff]]
    modId="bookshelf"
    mandatory=true
    versionRange="[8,)"
    ordering="AFTER"
    side="BOTH"
